### PR TITLE
Fix #2 - Return 5-day forecast

### LINKED ISSUE #2: Utilize OpenWeatherMap's API to return additional weather data (yargs, API, node)
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

**Are you interested in Node JS, and/or APIs? Then you've come to the right project!** This command line app allows a user to type in a location, then pulls weather data from [OpenWeatherMap's API](http://openweathermap.org/) and returns it to the user.

_If React JS, Node JS, APIs, HTML, Javascript, Webpack, Express, and/or SASS/CSS is more your thing, check out my other Hacktoberfest Project: [React-Weather-App](https://github.com/bmorelli25/React-Weather-App)! There are numerous [issues](https://github.com/bmorelli25/React-Weather-App/issues) to be solved - for all programming levels!_

**Your task:** Utilize OpenWeatherMaps API and return even more great data to the user. Using the [5 day/3 hour API](http://openweathermap.org/forecast5), return the 5 day forecast for the searched city if a user uses the `-f` flag or `-forecast` command. For help on how to do this, you can see my previous project [node-password-manager/app.js](https://github.com/bmorelli25/node-password-manager/blob/master/app.js).

Don't hesitate to reach out with questions, or if you need help understanding the code!

**Have an idea for a different improvement?** Awesome. I'll be opening up new issues all throughout Hacktoberfest - and please feel free to do the same! Want to implement a new feature, or found a bug? Open a new issue and start writing code!!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

### PR DESCRIPTION
**Pull request by m5r**
See it live :
cjrqjge

### CODE REVIEW

**Comment by bmorelli25** [comment]
@MomoGunz wow this looks AWESOME.

One big problem though - I merged a smaller update for this issue before your PR was submitted. There are now a lot of conflicts that must be resolved before Merging. I won't have time to work on these conflicts for a few days.. If you'd like, feel free to go through the conflicts and resolve yourself. I'll merge your PR next so that you don't have to do this again. Let me know if you're up for it!

**Comment by m5r** [comment]
I'm on it!

**Comment by bmorelli25** [comment]
Thanks @momogunz, I appreciate it!

**Comment by m5r** [comment]
No problem.
I noticed an issue in my code. I will try to get it fixed by tomorrow.

**Comment by m5r** [comment]
Hey,
I managed to get it done before going to bed. I'm closing this PR and opening the correct one.

**Pull request closed without merging**
